spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/java2_data
    username: checker
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl.auto: none
        jdbc:
          batch_size: 200
          batch_versioned_data: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8181